### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by mingkzhou** [RetroCirce/Music-SketchNet#2]
Thank you for your open source. Could you please provide the process code mentioned in the  3-1-MusicInpaintNet and 3-2-SketchVAE_InpaintRNN.

**Comment by RetroCirce** [comment]
Thank you for your attention in our code.
As I commented in the code, this can be easily implemented by using np.split.

If you want to use the Irish folk dataset, it has been provided in the google drive link.

If you want to use another dataset, just follow the below procedure:
1. Given a midi song with several measures (say 64 measures) (np.load)
2. Choose the measure sequence in 16 segment number in 8 hop size ( say 1-16 8-24 16-32 24-40 ....... 48-64) (np.split)
3. And use these as the input data for the next pipeline. (np.save)

Of course you can change the hop size, segment number. But just make sure you change the parameter in the later components.

We used np.load, np.split and np.save to do this. The reason for not providing the code here is because it is simple that we actually did not save the code lol. We just open a new ipython, type in 4-8 lines codes, and get the output, which is convenient since we can customize it depending on the dataset.

Hope this can help with you question.
